name: CI

on: [push]

jobs:
  test:
    name: Tests on ${{ matrix.go-version }}
    strategy:
      matrix:
        go-version: [1.12.9, 1.13]
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout
      uses: actions/checkout@v1
    - name: Go Test
      run: go test -v -cover ./...
